source 'https://github.com/CocoaPods/Specs.git'

target 'BFTask-Extras' do
  pod "BFTask-Extras", :path => "../"

  target 'Tests' do
    inherit! :search_paths
  	pod 'Specta'
  	pod 'Expecta'
  end
end